// SPDX-License-Identifier: MIT
// Copyright (c) 2026 The Bento authors
// Facade: the i18n ENGINE lives in the shared kernel (kernel/src/i18n.ts);
// the CATALOGS are this app's string data and stay here in ./i18n/*.ts.
//
// This module registers them at import time and re-exports the engine, so
// every consumer keeps importing './i18n' unchanged AND catalog registration
// is guaranteed to precede the first t() call by ES module evaluation order.
// App code must never import the kernel i18n directly — that would bypass
// this registration.

// The per-locale catalogs in ./i18n/*.ts are the SOURCE OF TRUTH (that is what
// a translator reviews and a contributor submits). What SHIPS is the key-once
// packing of them, generated by scripts/build-i18n.mjs — importing the
// per-locale files here instead would put every English key in the bundle
// seven times over. Regenerate after editing any catalog:
//
//     node scripts/build-i18n.mjs
//
import { PACKED, PACKED_LOCALES } from './i18n/packed'
import { registerI18n } from '../../kernel/src/i18n.ts'
import type { LocaleChoice } from '../../kernel/src/i18n.ts'

export type { Catalog } from '../../kernel/src/i18n.ts'

/** Locales offered in the About picker (label in its own language). */
const CHOICES: LocaleChoice[] = [
  { code: 'en', label: 'English' },
  { code: 'ja', label: '日本語' },
  { code: 'zh-Hans', label: '简体中文' },
  { code: 'zh-Hant', label: '繁體中文' },
  { code: 'es', label: 'Español' },
  { code: 'fr', label: 'Français' },
  { code: 'it', label: 'Italiano' },
  { code: 'de', label: 'Deutsch' },
]

registerI18n({
  packed: {
    locales: PACKED_LOCALES,
    table: PACKED,
    alias: {
      zh: 'zh-Hans', // zh, zh-CN, zh-SG → simplified
      'zh-CN': 'zh-Hans',
      'zh-SG': 'zh-Hans',
      'zh-TW': 'zh-Hant',
      'zh-HK': 'zh-Hant',
    },
  },
  choices: CHOICES,
})

/** Kept as a const export for call sites that read it directly. */
export const LOCALE_CHOICES = CHOICES

export { t, locale, setLocale, i18nApi, localeChoices } from '../../kernel/src/i18n.ts'
